export const API_BASE_URL = 'https://api.noroff.dev/api/v1';
export const API_REGISTER_URL = `${API_BASE_URL}/social/auth/register`;
export const API_LOGIN_URL = `${API_BASE_URL}/social/auth/login`;
export const API_ALL_POSTS = `${API_BASE_URL}/social/posts?_author=true`;
export const API_CREATE_POST = `${API_BASE_URL}/social/posts`;
export const queryString = document.location.search;
export const params = new URLSearchParams(queryString);
export const id = params.get("id");
export const API_SINGLE_POST = `${API_BASE_URL}/social/posts/${id}`;
export const errorMessageElement = document.getElementById('error-message');
